
[functions]
  [functions.import_map]
  inherit_default_cors = true

[functions.protocol]
protocol = "http"

[functions.send-email]
verify_jwt = false

[functions.send-mortgage-report]
verify_jwt = false

