services:
  postgres:
    build:
      context: ./db
      dockerfile: Dockerfile
    environment:
      POSTGRES_DB: property_db
      POSTGRES_USER: property_user
      POSTGRES_PASSWORD: property_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U property_user -d property_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    stop_grace_period: 30s
    restart: unless-stopped
    stop_signal: SIGINT

  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/property_db
      SPRING_DATASOURCE_USERNAME: property_user
      SPRING_DATASOURCE_PASSWORD: property_pass
      SPRING_FLYWAY_REPAIR: "true"
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
    volumes:
      - ./back-end/src:/app/src
      - ./back-end/pom.xml:/app/pom.xml
      - backend_maven_repo:/root/.m2
    depends_on:
      postgres:
        condition: service_healthy
    stop_grace_period: 20s

  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    volumes:
      - ./front-end:/app
      - frontend_node_modules:/app/node_modules
    ports:
      - "3001:3001"
    environment:
      - VITE_API_URL=http://localhost:8080
    depends_on:
      - backend

volumes:
  postgres_data:
  backend_maven_repo:
  frontend_node_modules: 