version: '3.8'

services:
  # Database service (PostgreSQL)
  postgres:
    image: postgres:15-alpine
    container_name: property_postgres
    environment:
      POSTGRES_DB: property_db
      POSTGRES_USER: property_user
      POSTGRES_PASSWORD: property_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U property_user -d property_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - property_network

  # Backend service (Spring Boot)
  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile.prod
    container_name: property_backend
    ports:
      - "8080:8080"
    env_file:
      - ./back-end/.env
    environment:
      - SERVER_ADDRESS=0.0.0.0
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=prod
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - property_network

  # Frontend service (React with Vite)
  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile.prod
    container_name: property_frontend
    ports:
      - "3001:80"
    environment:
      - VITE_API_URL=http://backend:8080
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - property_network

# Define custom network
networks:
  property_network:
    driver: bridge

# Persistent volumes
volumes:
  postgres_data:
    driver: local 