version: '3.8'

services:
  # Database service (PostgreSQL)
  postgres:
    image: postgres:15-alpine
    container_name: property_postgres
    environment:
      POSTGRES_DB: property_db
      POSTGRES_USER: property_user
      POSTGRES_PASSWORD: property_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U property_user -d property_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Backend service (Spring Boot)
  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    container_name: property_backend
    ports:
      - "8080:8080"
    env_file:
      - ./back-end/.env
    environment:
      - SERVER_ADDRESS=134.199.160.11
      - SERVER_PORT=8080
    volumes:
      - ./back-end/src:/app/src
      - ./back-end/pom.xml:/app/pom.xml
      - backend_maven_repo:/root/.m2
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s
    depends_on:
      - postgres
    restart: unless-stopped

  # Frontend service (React with Vite)
  # Note: Running on ubuntu-s-1vcpu-1gb-syd1-01 (134.199.160.11)
  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    container_name: property_frontend
    volumes:
      - ./front-end:/app
      - frontend_node_modules:/app/node_modules
    ports:
      - "3001:3001"
    environment:
      - VITE_API_URL=http://134.199.160.11:8080
      - HOST=0.0.0.0
      - PORT=3001
    depends_on:
      - backend
    restart: unless-stopped
    command: npm run dev -- --host 0.0.0.0 --port 3001

# Persistent volumes
volumes:
  postgres_data:
    driver: local
  backend_maven_repo:
    driver: local
  frontend_node_modules:
    driver: local 