services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: property_db
      POSTGRES_USER: property_user
      POSTGRES_PASSWORD: property_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U property_user -d property_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./back-end/.env
    volumes:
      - ./back-end/src:/app/src
      - ./back-end/pom.xml:/app/pom.xml
      - backend_maven_repo:/root/.m2
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/api/health"]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 60s
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    volumes:
      - ./front-end:/app
      - frontend_node_modules:/app/node_modules
    ports:
      - "3001:3001"
    env_file:
      - ./front-end/.env
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
  backend_maven_repo:
  frontend_node_modules: 