// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bykgpwwagvxxbrpubxbz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ5a2dwd3dhZ3Z4eGJycHVieGJ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxMzQzNzIsImV4cCI6MjA1ODcxMDM3Mn0.osNLuzpyY9jC8NFL9U7AW7kbcrZDGGshnJ4roxs3zcM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);