spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/property_db
    username: property_user
    password: property_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        type:
          uuid: org.hibernate.type.UUIDCharType
    open-in-view: false

server:
  port: 8080 